### ISSUE TITLE
Consistency of spherical harmonic interface

### ISSUE THREAD

**Issue by anowacki** [mantle-convection-constrained/terratools#100]
The spherical harmonic analysis stuff in `terra_model.TerraModel` works a bit differently to the rest of the stuff in the class.  For example:

- `hp_sph` takes in an array, rather than a field name
- It's currently undocumented
- It also stores spherical harmonics in a public attribute, whereas all the others are private
- There is no accessor function to get spherical harmonics for a field.  (Maybe `TerraModel.get_spherical_harmonics(field)`?)
- `_pixelise` doesn't need to be in the `TerraModel` class as it doesn't use any information from a model

It would be nice for consistency to get this working like the other bits of `TerraModel`s before v1.0.

**Comment by jamespanton93** [comment]
Yeah this is my mess to sort out so I'll get stuck in to it.
