### ISSUE TITLE
Docs builds are broken

### ISSUE THREAD

**Issue by anowacki** [mantle-convection-constrained/terratools#120]
Currently [docs are not building](https://readthedocs.org/projects/terratools/builds/21909144/) because the [`watch` option to the `mkdocstrings` plugin in `mkdocs.yml`](https://github.com/mantle-convection-constrained/terratools/blob/07e78dd25f3163161a72d20042d40e63fbf5cc0b/mkdocs.yml#L27) is no longer recognised.

**Comment by bobmyhill** [comment]
Fixed in #122
