### ISSUE TITLE
Enable PR docs builds

### ISSUE THREAD

**Issue by anowacki** [mantle-convection-constrained/terratools#121]
We don't currently build docs in PRs, but it would be good to:

> It would be nice to have PR docs builds.  @bobmyhill are you able to help here?  You nicely set all the doc building up for us.

_Originally posted by @anowacki in https://github.com/mantle-convection-constrained/terratools/issues/112#issuecomment-1717403041_

**Comment by bobmyhill** [comment]
Fixed by ticking a box in readthedocs.
