### ISSUE TITLE
Code formatting

### ISSUE THREAD

**Issue by anowacki** [mantle-convection-constrained/terratools#19]
I think it would be nice to enforce a particular code formatting convention so we can just run a formatter automatically.

**Comment by bobmyhill** [comment]
Agreed (at least in principle). Any preference?

**Comment by bobmyhill** [comment]
https://black.readthedocs.io/en/stable/ is good

**Comment by bobmyhill** [comment]
The others approve :)

**Comment by bobmyhill** [comment]
Resolved by #59.
