### ISSUE TITLE
Enable 'vectorised' `terra_model.TerraModel.evaluate` for triangle interpolation

### ISSUE THREAD

**Issue by anowacki** [mantle-convection-constrained/terratools#29]
When using spherical triangle interpolation, `evaluate` does not currently accept non-scalar arguments since it finds the three nearest neighbours to the point of interest, and it is not written to do this with more than one point at a time.  It might be beneficial to see if it can be adjusted to work in a 'vectorised' way.

Alternatively, if Numba or something else can be used to speed this up as well as 'vectorise' this, that would be nice.

At present, the `"triangle"` interpolation method for `evaluate` is a bit too sluggish to make nice plots.

**Comment by andreww** [comment]
Once I've got my test environment working I'm happy to look at this. From a quick peek I think it's just a case of adding the numba.vectorize decorator, but I don't think I've tried that with a method rather than a bare function. But if that's an issue it's easy to work around.

**Comment by bobmyhill** [comment]
geographic.spherical_triangle_area is one function that still needs vectorising.

**Comment by anowacki** [comment]
Closed by #75.
