### ISSUE TITLE
CI: Error building cartopy

### ISSUE THREAD

**Issue by anowacki** [mantle-convection-constrained/terratools#30]
cartopy is currently [failing to build on the GitHub Actions workers](https://github.com/mantle-convection-constrained/terratools/actions/runs/3098286462/jobs/5016009557#step:5:296), causing CI errors and preventing automated testing.  We need to fix this before #28 and its ancestors can be merged.

**Comment by anowacki** [comment]
Looks like we are not alone:

- https://github.com/SciTools/cartopy/issues/1239
- https://github.com/SciTools/cartopy/issues/535

It looks like the answer is to install some binary dependencies manually, which seems unfortunate.

**Comment by bobmyhill** [comment]
@anowacki should be fixed now (GitHub actions needed libgeos-dev, as you suggested)

**Comment by anowacki** [comment]
Great, thanks!

We now need to tell users about this—added a reminder to #32.
