### ISSUE TITLE
Docstring consistency

### ISSUE THREAD

**Issue by anowacki** [mantle-convection-constrained/terratools#31]
We should use a consistent docstring format that can be automatically made into web pages for reference purposes.  I have generally used ReST-formatted docstring in the [Sphinx style](https://sphinx-rtd-tutorial.readthedocs.io/en/latest/docstrings.html), but I haven't used cross-referencing and other features.  Likewise, lots of other code doesn't use this format.

We should decide on a format and ensure it's used consistently.

**Comment by anowacki** [comment]
Great, thanks Bob!  Let's stick with the Sphynx style you and I have used from now on, then (linked to [above](https://github.com/mantle-convection-constrained/terratools/issues/31#issue-1380974891).

It looks like it would be good for `terra_model.py` to add types, and for `lookup_tables.py` to switch to this format (@eejwa and @jamespanton93).

I think we can close this when all the current docstrings are the same then.

**Comment by eejwa** [comment]
Okay, no problem. I can change the docstrings in lookup_tables.py.

**Comment by bobmyhill** [comment]
@anowacki, @eejwa I've edited the docstrings throughout the code so that they render reasonably. But some of the docstrings could do with some more work to make it clear what each function does, the types of each input and output parameter, etc.

**Comment by anowacki** [comment]
#98 mentions this now, but of course consistency will need to be watched for in PRs.  Possibly adding a mention to `.github/PULL_REQUEST_TEMPLATE.md` may be useful.
